const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "ApiPeliculas",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:4000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "peliculas"
            // "description": "Endpoints"
        }
    ],
    // securityDefinitions: {
    //     apiKeyAuth:{
    //         type: "apiKey",
    //         in: "header",       // can be "header", "query" or "cookie"
    //         name: "X-API-KEY",  // name of the header, query parameter or cookie
    //         description: "any description..."
    //     }
    // },
    definitions: {
        Pelicula: {
            title:"Guardians of the Galaxy Vol. 2",
            year: "2017",
            released: "05 May 2017",
            genre: "Action, Adventure, Comedy",
            director: "James Gunn",
            actors: "Chris Pratt, Zoe Saldana, Dave Bautista",
            plot: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",
            ratings: [
                {
                    Source: "Internet Movie Database",
                    Value: "7.6/10"
                },
                {
                    Source: "Rotten Tomatoes",
                    Value: "85%"
                },
                {
                    Source: "Metacritic",
                    Value: "67/100"
                }
            ]
        },
        consultaActualizaPelicula: {
            movie: "Guardians of the Galaxy Vol. 2",
            find: "father",
            replace: "brother",
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')
});